name: C/C++ CI

on:
  push:
    branches: [ "main", "5-change-behavior-to-not-use-static-variable" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: Bacondish2023/setup-googletest@v1.0.1
    - name: Install dependencies
      run: autoreconf --install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
