name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  tag:
    name: Tag version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
  release:
    runs-on: ubuntu-latest
    needs: tag
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: Bacondish2023/setup-googletest@v1.0.1
    - name: Install dependencies
      run: autoreconf --install
    - name: Configure
      run: ./configure
    - name: make
      run: make dist
    - uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "libargparse-*.tar.gz"
        generateReleaseNotes: true
        tag: ${{ needs.tag.outputs.tag }}
      name: Release
