name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: Bacondish2023/setup-googletest@v1.0.1
    - name: Install dependencies
      run: autoreconf --install
    - name: Configure
      run: ./configure
    - name: make
      run: make dist
    - uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "libargparse-*.tar.gz"
        generateReleaseNotes: true
      name: Release
